<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Hamster Clicker Report</title>
    <style>
        body {
            font-family: sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        h1 {
            color: #2d3748;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        .stats {
            margin-top: 30px;
        }
        .stat-card {
            background: #f7fafc;
            padding: 15px;
            margin: 10px 0;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #cbd5e0;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #edf2f7;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #718096;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <h1>🐹 Hamster Clicker Report</h1>
    
    <div class="stat-card">
        <strong>User:</strong> {{ $user->email }}<br>
        <strong>Generated:</strong> {{ $generatedAt }}
    </div>

    <div class="stats">
        <h3>Summary Statistics</h3>
        <div class="stat-card">
            <strong>Total clicks:</strong> {{ $total }}<br>
            <strong>Clicks today:</strong> {{ $today }}
        </div>

        <h3>Last 7 Days Activity</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Clicks</th>
                </tr>
            </thead>
            <tbody>
                @foreach($last7Days as $day)
                <tr>
                    <td>{{ $day->date }}</td>
                    <td style="text-align: center">{{ $day->count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by Hamster Clicker • {{ date('Y') }}
    </div>
</body>
</html>